import Head from "next/head";


import BlogPostPage from "../components/blog-post-page";


export default function BlogRead(props) {
  return (
    <div>
      <Head>
        <title>SSS Proxima - Blog Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BlogPostPage data={props.data} />
    </div>
  );
}






