import Head from 'next/head'
import Image from 'next/image'
import BlogPostPage from '../components/blog-page'
import PostCard from '../components/post-card'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SSS Blog - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <BlogPostPage /> */}
      <main className={styles.main}>
        <div className={styles.grid}>
          <PostCard/>
          <PostCard/>
          <PostCard/>
          <PostCard/>
          <PostCard/>
          <PostCard/>
          <PostCard/>
          <PostCard/>
          <PostCard/>
          <PostCard/>
        </div>
      </main>
    </div>
  );
}
